import type { JobOffer } from "@/lib/job-types";

export const mockJobs: JobOffer[] = [
  {
    id: "jr-001",
    sourceId: "ft-1001",
    source: "france_travail",
    title: "Product Manager – Plateforme RH",
    company: "Swile",
    location: { city: "Paris", department: "75", region: "Ile-de-France", coords: { lat: 48.8566, lng: 2.3522 } },
    contractType: "CDI",
    salary: { min: 55000, max: 70000, currency: "EUR", period: "year" },
    remote: "partial",
    experienceLevel: "mid",
    sector: "HR Tech",
    description: "Piloter la roadmap produit d'une plateforme RH SaaS utilisée par 10 000 entreprises. Vous travaillerez en squad avec 3 devs et 1 designer.",
    skills: ["Product Management", "Agile", "SQL", "Figma"],
    publishedAt: "2026-04-21T08:00:00.000Z",
    applyUrl: "https://swile.co/jobs/pm-rh",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-002",
    sourceId: "wttj-2209",
    source: "wttj",
    title: "Lead Développeur Fullstack TypeScript",
    company: "Alan",
    location: { city: "Paris", department: "75", region: "Ile-de-France", coords: { lat: 48.8488, lng: 2.3709 } },
    contractType: "CDI",
    salary: { min: 70000, max: 90000, currency: "EUR", period: "year" },
    remote: "full",
    experienceLevel: "senior",
    sector: "Insurtech",
    description: "Tech lead sur l'équipe core platform. Stack : Node.js, React, PostgreSQL, Kubernetes. Vous encadrez 4 développeurs.",
    skills: ["TypeScript", "Node.js", "React", "PostgreSQL"],
    publishedAt: "2026-04-20T14:00:00.000Z",
    applyUrl: "https://jobs.alan.com/lead-dev",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-003",
    sourceId: "linkedin-788",
    source: "linkedin",
    title: "Data Analyst – Marketing",
    company: "BlaBlaCar",
    location: { city: "Paris", department: "75", region: "Ile-de-France", coords: { lat: 48.8529, lng: 2.3499 } },
    contractType: "CDI",
    salary: { min: 45000, max: 58000, currency: "EUR", period: "year" },
    remote: "partial",
    experienceLevel: "junior",
    sector: "Mobilité",
    description: "Analyser les campagnes marketing sur 20 pays. Vous construisez des dashboards Looker et participez aux décisions growth.",
    skills: ["SQL", "Looker", "Python", "Google Analytics"],
    publishedAt: "2026-04-20T10:30:00.000Z",
    applyUrl: "https://blablacar.com/jobs/data-analyst",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-004",
    sourceId: "apec-3301",
    source: "apec",
    title: "Ingénieur Logiciel Embarqué C++",
    company: "Airbus",
    location: { city: "Toulouse", department: "31", region: "Occitanie", coords: { lat: 43.6047, lng: 1.4442 } },
    contractType: "CDI",
    salary: { min: 52000, max: 65000, currency: "EUR", period: "year" },
    remote: "none",
    experienceLevel: "mid",
    sector: "Aéronautique",
    description: "Développement de logiciels embarqués critiques pour les systèmes avioniques A320. Certification DO-178C.",
    skills: ["C++", "RTOS", "DO-178C", "Git"],
    publishedAt: "2026-04-19T09:00:00.000Z",
    applyUrl: "https://airbus.com/careers/embedded-dev",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-005",
    sourceId: "ft-5512",
    source: "france_travail",
    title: "UX Designer – Applications Mobiles",
    company: "Doctolib",
    location: { city: "Lyon", department: "69", region: "Auvergne-Rhône-Alpes", coords: { lat: 45.7578, lng: 4.832 } },
    contractType: "CDI",
    salary: { min: 48000, max: 60000, currency: "EUR", period: "year" },
    remote: "partial",
    experienceLevel: "mid",
    sector: "Health Tech",
    description: "Concevoir les flows de prise de rendez-vous médicaux sur iOS et Android. Vous participez aux tests utilisateurs hebdomadaires.",
    skills: ["Figma", "Prototyping", "User Research", "Design System"],
    publishedAt: "2026-04-21T07:10:00.000Z",
    applyUrl: "https://doctolib.fr/jobs/ux-designer-lyon",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-006",
    sourceId: "hellowork-8821",
    source: "hellowork",
    title: "Alternance – Développeur React",
    company: "Capgemini",
    location: { city: "Bordeaux", department: "33", region: "Nouvelle-Aquitaine", coords: { lat: 44.8378, lng: -0.5792 } },
    contractType: "Alternance",
    salary: { min: 18000, max: 22000, currency: "EUR", period: "year" },
    remote: "partial",
    experienceLevel: "junior",
    sector: "Conseil IT",
    description: "Rejoignez l'équipe frontend pour développer des interfaces React pour nos clients grands comptes. Rythme 3j école / 2j entreprise.",
    skills: ["React", "JavaScript", "CSS", "Git"],
    publishedAt: "2026-04-18T11:00:00.000Z",
    applyUrl: "https://capgemini.com/alternance-react-bordeaux",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-007",
    sourceId: "wttj-9934",
    source: "wttj",
    title: "DevOps Engineer – Cloud AWS",
    company: "OVHcloud",
    location: { city: "Lille", department: "59", region: "Hauts-de-France", coords: { lat: 50.6292, lng: 3.0573 } },
    contractType: "CDI",
    salary: { min: 58000, max: 72000, currency: "EUR", period: "year" },
    remote: "full",
    experienceLevel: "senior",
    sector: "Cloud",
    description: "Gérer l'infrastructure cloud OVH : Kubernetes, Terraform, CI/CD GitLab. On-call 1 semaine sur 4.",
    skills: ["Kubernetes", "Terraform", "AWS", "GitLab CI"],
    publishedAt: "2026-04-17T15:00:00.000Z",
    applyUrl: "https://ovhcloud.com/jobs/devops-lille",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-008",
    sourceId: "apec-7721",
    source: "apec",
    title: "Chef de Projet Digital",
    company: "Sanofi",
    location: { city: "Strasbourg", department: "67", region: "Grand Est", coords: { lat: 48.5734, lng: 7.7521 } },
    contractType: "CDD",
    salary: { min: 44000, max: 54000, currency: "EUR", period: "year" },
    remote: "partial",
    experienceLevel: "mid",
    sector: "Pharma",
    description: "Piloter la refonte du portail médecins Sanofi France. Coordination avec les équipes IT Paris et les prestataires externes.",
    skills: ["Gestion de projet", "Jira", "Confluence", "Agile"],
    publishedAt: "2026-04-16T09:30:00.000Z",
    applyUrl: "https://sanofi.com/jobs/cdp-digital-strasbourg",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-009",
    sourceId: "linkedin-4421",
    source: "linkedin",
    title: "Ingénieur Machine Learning",
    company: "Criteo",
    location: { city: "Paris", department: "75", region: "Ile-de-France", coords: { lat: 48.8701, lng: 2.3477 } },
    contractType: "CDI",
    salary: { min: 75000, max: 95000, currency: "EUR", period: "year" },
    remote: "partial",
    experienceLevel: "senior",
    sector: "AdTech",
    description: "Développer et entraîner des modèles de recommandation publicitaire servant 5 milliards d'impressions par jour.",
    skills: ["Python", "PyTorch", "Spark", "MLflow"],
    publishedAt: "2026-04-21T06:00:00.000Z",
    applyUrl: "https://criteo.com/jobs/ml-engineer",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-010",
    sourceId: "ft-6630",
    source: "france_travail",
    title: "Stage – Product Design",
    company: "Decathlon Digital",
    location: { city: "Lille", department: "59", region: "Hauts-de-France", coords: { lat: 50.6178, lng: 3.0717 } },
    contractType: "Stage",
    salary: { min: 1100, max: 1300, currency: "EUR", period: "month" },
    remote: "partial",
    experienceLevel: "junior",
    sector: "Retail",
    description: "Stage de 6 mois dans l'équipe Design System Decathlon. Vous participez à la refonte des composants mobile de l'app Decathlon.",
    skills: ["Figma", "Design System", "Prototypage"],
    publishedAt: "2026-04-15T10:00:00.000Z",
    applyUrl: "https://decathlon.fr/jobs/stage-design",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-011",
    sourceId: "wttj-1122",
    source: "wttj",
    title: "Backend Engineer – Rust / Go",
    company: "Ledger",
    location: { city: "Paris", department: "75", region: "Ile-de-France", coords: { lat: 48.8611, lng: 2.3575 } },
    contractType: "CDI",
    salary: { min: 80000, max: 100000, currency: "EUR", period: "year" },
    remote: "partial",
    experienceLevel: "senior",
    sector: "Crypto / Fintech",
    description: "Développer les services cryptographiques bas-niveau du Ledger hardware wallet. Performance critique, zéro tolérance aux bugs.",
    skills: ["Rust", "Go", "Cryptographie", "Linux"],
    publishedAt: "2026-04-20T16:00:00.000Z",
    applyUrl: "https://ledger.com/jobs/backend-rust",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-012",
    sourceId: "apec-5544",
    source: "apec",
    title: "Responsable Marketing Acquisition",
    company: "ManoMano",
    location: { city: "Bordeaux", department: "33", region: "Nouvelle-Aquitaine", coords: { lat: 44.8312, lng: -0.5757 } },
    contractType: "CDI",
    salary: { min: 50000, max: 63000, currency: "EUR", period: "year" },
    remote: "partial",
    experienceLevel: "mid",
    sector: "E-commerce",
    description: "Piloter les campagnes SEA / Meta Ads / Affiliation pour le marché français. Budget mensuel de 800k€.",
    skills: ["Google Ads", "Meta Ads", "SEA", "Analytics"],
    publishedAt: "2026-04-19T13:00:00.000Z",
    applyUrl: "https://manomano.fr/jobs/marketing-acquisition",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
];
