import type { JobOffer } from "@/lib/job-types";

export const mockJobs: JobOffer[] = [
  {
    id: "jr-001",
    sourceId: "ft-1001",
    source: "france_travail",
    title: "Product Marketing Manager Spatial Tech",
    company: "Orbital Insights SAS",
    location: {
      city: "Paris",
      department: "75",
      region: "Ile-de-France",
      coords: { lat: 48.8589, lng: 2.3469 },
    },
    contractType: "CDI",
    salary: { min: 52000, max: 68000, currency: "EUR", period: "year" },
    remote: "partial",
    experienceLevel: "mid",
    sector: "Aerospace",
    description: "Piloter la strategie go-to-market d une plateforme data spatiale.",
    skills: ["Product Marketing", "B2B SaaS", "Data Storytelling"],
    publishedAt: "2026-04-20T09:30:00.000Z",
    applyUrl: "https://example.com/jobs/ft-1001",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-002",
    sourceId: "apec-2209",
    source: "apec",
    title: "Growth Manager Education",
    company: "ISU Learning Lab",
    location: {
      city: "Strasbourg",
      department: "67",
      region: "Grand Est",
      coords: { lat: 48.5839, lng: 7.7455 },
    },
    contractType: "CDD",
    salary: { min: 38000, max: 46000, currency: "EUR", period: "year" },
    remote: "none",
    experienceLevel: "junior",
    sector: "Education",
    description: "Accelerer la croissance d un programme e-learning spatial.",
    skills: ["Growth", "CRM", "Analytics"],
    publishedAt: "2026-04-19T13:45:00.000Z",
    applyUrl: "https://example.com/jobs/apec-2209",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
  {
    id: "jr-003",
    sourceId: "linkedin-788",
    source: "linkedin",
    title: "Frontend Engineer Map Experiences",
    company: "CartoNova SA",
    location: {
      city: "Lyon",
      department: "69",
      region: "Auvergne-Rhone-Alpes",
      coords: { lat: 45.7578, lng: 4.832 },
    },
    contractType: "CDI",
    salary: { min: 50000, max: 62000, currency: "EUR", period: "year" },
    remote: "full",
    experienceLevel: "mid",
    sector: "Software",
    description: "Developper des experiences cartographiques pour un produit RH data-driven.",
    skills: ["Next.js", "TypeScript", "Mapbox"],
    publishedAt: "2026-04-21T07:10:00.000Z",
    applyUrl: "https://example.com/jobs/linkedin-788",
    isDuplicate: false,
    crawledAt: "2026-04-21T08:00:00.000Z",
  },
];
